const data = {
    products: [
        {
            name: 'Free Shirt',
            catagory: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 40,
            brand: 'Zara',
            rating: '4.5',
            numReviews: '8',
            countInStock: '18',
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            catagory: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 60,
            brand: 'Infinity',
            rating: '4.6',
            numReviews: '10',
            countInStock: '20',
            description: 'A popular shirt',
        },
        {
            name: 'Long Shirt',
            catagory: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 70,
            brand: 'Nike',
            rating: '4.8',
            numReviews: '12',
            countInStock: '7',
            description: 'A popular shirt',
        },
        {
            name: 'Golf pant',
            catagory: 'Pants',
            image: '/images/pants1.jpg',
            price: 30,
            brand: 'Avis',
            rating: '4.7',
            numReviews: '9',
            countInStock: '10',
            description: 'A popular pant',
        },
        {
            name: 'Slim pant',
            catagory: 'Pants',
            image: '/images/pants2.jpg',
            price: 60,
            brand: 'Easy',
            rating: '5',
            numReviews: '18',
            countInStock: '30',
            description: 'A popular pant',
        },
        {
            name: 'Classic pant',
            catagory: 'Pants',
            image: '/images/pants3.jpg',
            price: 40,
            brand: 'Zara',
            rating: '4.5',
            numReviews: '8',
            countInStock: '18',
            description: 'A popular pant',
        },
    ],
};

export default data;